# Internal consistency: ratio of new to old population {#newoldpop}
Chart of ratio of new vs. old population counts in Lexis database.  Might be used to locate large discrepancies between old and new data.
```{r pb17, include=FALSE}
if(usingShiny==1){
  progress$set(detail="Ratio of new to old Population",value = 17/18)
}
```

## Females
```{r plotNumberRatioFp, cache=TRUE,   fig.cap='Internal consistency: ratio of new to old population',  fig.align='center',  fig.height=10, out.width="95%",fig.asp=1, dpi=150}
mydata=plotNumberRatio(parms, sex='f', type="pop")
if (is.na(mydata[1,1])) {print("No extreme observations for females.")} else {
  knitr::kable(
    mydata, booktabs = TRUE,
    caption = 'List of Extreme Observations, Female'
    )
}
```

## Males
```{r plotNumberRatioMp, cache=TRUE,   fig.cap='Internal consistency: ratio of new to old population',  fig.align='center',  fig.height=10, out.width="95%",fig.asp=1, dpi=150}
mydata=plotNumberRatio(parms, sex='m', type="pop")
if (is.na(mydata[1,1])) {print("No extreme observations for males.")} else {
  knitr::kable(
    mydata, booktabs = TRUE,
    caption = 'List of Extreme Observations, Male'
    )
}
```
